### ISSUE TITLE
Overestimates entropy by a large factor

### ISSUE THREAD

**Issue by kroeckx** [ynezz/openwrt-urngd#2]
I've been looking at what jitterentropy does, and can only conclude that it overestimates the entropy that was collected.

My current understanding of the code is that it internally calls jent_measure_jitter(), which is responsible for returning the random data. It returns that in groups of 256 bit (32 byte). My current estimate is that such groups of 256 bit contains less than 0.01 bit of entropy on my non-idle desktop system. urngd seems to get 2 such blocks, and tells the kernel that it contains the entropy of 1 block. So I think we get less then 0.02 bit of entropy, but tell the kernel it contains 256 bit of entropy, overestimating the entopy by a factor of at least 12800.

**Comment by ynezz** [comment]
@kroeckx Thanks for looking into urngd, but I think, that this is wrong place for discussing potential issues in the underlying jitterentropy-rngd library, the upstream project lives here https://github.com/smuellerDD/jitterentropy-rngd/issues so please report it there.

This repository is just my personal playground, OpenWrt project lives here https://git.openwrt.org/project/urngd.git and https://openwrt.org/submitting-patches with https://openwrt.org/bugs applies there.
